name: GHA BUILD
# run desctiption
run-name: trying to build an image using gha
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u DOCKER_USER -p $DOCKER_PASS
    - name: docker build
      run: docker build . --file Dockerfile --tag tomsenyah/dicicd:${{ github.sha }}
    - name: docker push
      run: docker push tomsenyah/dicicd:${{ github.sha }}